import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import pandas as pd

urls = [
    "https://www.bodybuilding.com/exercises/rickshaw-carry",
    "https://www.bodybuilding.com/exercises/single-leg-press",
    "https://www.bodybuilding.com/exercises/landmine-180s",
    "https://www.bodybuilding.com/exercises/weighted-pull-ups",
    "https://www.bodybuilding.com/exercises/t-bar-row-with-handle",
    "https://www.bodybuilding.com/exercises/palms-down-wrist-curl-over-a-bench",
    "https://www.bodybuilding.com/exercises/atlas-stones",
    "https://www.bodybuilding.com/exercises/side-laterals-to-front-raise-",
    "https://www.bodybuilding.com/exercises/clean-from-blocks",
    "https://www.bodybuilding.com/exercises/incline-hammer-curls",
    "https://www.bodybuilding.com/exercises/wrist-rotations-with-straight-bar",
    "https://www.bodybuilding.com/exercises/barbell-glute-bridge",
    "https://www.bodybuilding.com/exercises/clean-and-press",
    "https://www.bodybuilding.com/exercises/dips-triceps-version",
    "https://www.bodybuilding.com/exercises/farmers-walk",
    "https://www.bodybuilding.com/exercises/palms-up-barbell-wrist-curl-over-a-bench",
    "https://www.bodybuilding.com/exercises/barbell-full-squat",
    "https://www.bodybuilding.com/exercises/deficit-deadlift",
    "https://www.bodybuilding.com/exercises/barbell-deadlift",
    "https://www.bodybuilding.com/exercises/standing-palm-in-one-arm-dumbbell-press",
    "https://www.bodybuilding.com/exercises/romanian-deadlift-with-dumbbells",
    "https://www.bodybuilding.com/exercises/tire-flip",
    "https://www.bodybuilding.com/exercises/clean-deadlift",
    "https://www.bodybuilding.com/exercises/plank",
    "https://www.bodybuilding.com/exercises/bottoms-up",
    "https://www.bodybuilding.com/exercises/box-squat",
    "https://www.bodybuilding.com/exercises/clean-and-jerk",
    "https://www.bodybuilding.com/exercises/one-arm-kettlebell-push-press",
    "https://www.bodybuilding.com/exercises/push-press",
    "https://www.bodybuilding.com/exercises/suspended-fallout",
    "https://www.bodybuilding.com/exercises/standing-military-press",
    "https://www.bodybuilding.com/exercises/snatch",
    "https://www.bodybuilding.com/exercises/sumo-deadlift",
    "https://www.bodybuilding.com/exercises/hang-clean",
    "https://www.bodybuilding.com/exercises/dumbbell-v-sit-cross-jab",
    "https://www.bodybuilding.com/exercises/reverse-band-box-squat",
    "https://www.bodybuilding.com/exercises/standing-palms-in-dumbbell-press",
    "https://www.bodybuilding.com/exercises/standing-cable-lift",
    "https://www.bodybuilding.com/exercises/decline-ez-bar-triceps-extension",
    "https://www.bodybuilding.com/exercises/standing-palms-up-barbell-behind-the-back-wrist-curl",
    "https://www.bodybuilding.com/exercises/finger-curls",
    "https://www.bodybuilding.com/exercises/wide-grip-standing-barbell-curl",
    "https://www.bodybuilding.com/exercises/spell-caster",
    "https://www.bodybuilding.com/exercises/dumbbell-floor-press",
    "https://www.bodybuilding.com/exercises/lying-face-down-plate-neck-resistance",
    "https://www.bodybuilding.com/exercises/pullups",
    "https://www.bodybuilding.com/exercises/decline-reverse-crunch",
    "https://www.bodybuilding.com/exercises/dumbbell-bench-press",
    "https://www.bodybuilding.com/exercises/rope-jumping",
    "https://www.bodybuilding.com/exercises/seated-barbell-military-press",
    "https://www.bodybuilding.com/exercises/spider-curl",
    "https://www.bodybuilding.com/exercises/smith-machine-shrug",
    "https://www.bodybuilding.com/exercises/smith-machine-calf-raise",
    "https://www.bodybuilding.com/exercises/romanian-deadlift-from-deficit",
    "https://www.bodybuilding.com/exercises/power-snatch",
    "https://www.bodybuilding.com/exercises/pushups",
    "https://www.bodybuilding.com/exercises/barbell-walking-lunge",
    "https://www.bodybuilding.com/exercises/front-squats-with-two-kettlebells",
    "https://www.bodybuilding.com/exercises/spider-crawl",
    "https://www.bodybuilding.com/exercises/power-clean-from-blocks",
    "https://www.bodybuilding.com/exercises/single-leg-push-off",
    "https://www.bodybuilding.com/exercises/hip-circles-prone",
    "https://www.bodybuilding.com/exercises/reverse-grip-bent-over-rows",
    "https://www.bodybuilding.com/exercises/seated-two-arm-palms-up-low-pulley-wrist-curl",
    "https://www.bodybuilding.com/exercises/hyperextensions-back-extensions",
    "https://www.bodybuilding.com/exercises/close-grip-barbell-bench-press",
    "https://www.bodybuilding.com/exercises/cocoons",
    "https://www.bodybuilding.com/exercises/cross-body-crunch",
    "https://www.bodybuilding.com/exercises/hammer-curls",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-press",
    "https://www.bodybuilding.com/exercises/dumbbell-flyes",
    "https://www.bodybuilding.com/exercises/low-cable-crossover",
    "https://www.bodybuilding.com/exercises/one-arm-high-pulley-cable-side-bends",
    "https://www.bodybuilding.com/exercises/seated-dumbbell-press",
    "https://www.bodybuilding.com/exercises/standing-dumbbell-press",
    "https://www.bodybuilding.com/exercises/single-leg-push-off",
    "https://www.bodybuilding.com/exercises/hip-circles-prone",
    "https://www.bodybuilding.com/exercises/reverse-grip-bent-over-rows",
    "https://www.bodybuilding.com/exercises/seated-two-arm-palms-up-low-pulley-wrist-curl",
    "https://www.bodybuilding.com/exercises/hyperextensions-back-extensions",
    "https://www.bodybuilding.com/exercises/close-grip-barbell-bench-press",
    "https://www.bodybuilding.com/exercises/cocoons",
    "https://www.bodybuilding.com/exercises/cross-body-crunch",
    "https://www.bodybuilding.com/exercises/dumbbell-flyes",
    "https://www.bodybuilding.com/exercises/hammer-curls",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-press",
    "https://www.bodybuilding.com/exercises/seated-dumbbell-press",
    "https://www.bodybuilding.com/exercises/standing-dumbbell-press",
    "https://www.bodybuilding.com/exercises/ez-bar-curl",
    "https://www.bodybuilding.com/exercises/olympic-squat-",
    "https://www.bodybuilding.com/exercises/natural-glute-ham-raise",
    "https://www.bodybuilding.com/exercises/axle-deadlift",
    "https://www.bodybuilding.com/exercises/zottman-curl",
    "https://www.bodybuilding.com/exercises/floor-glute-ham-raise",
    "https://www.bodybuilding.com/exercises/one-arm-side-laterals",
    "https://www.bodybuilding.com/exercises/power-partials",
    "https://www.bodybuilding.com/exercises/leverage-shrug",
    "https://www.bodybuilding.com/exercises/triceps-pushdown-v-bar-attachment",
    "https://www.bodybuilding.com/exercises/wrist-roller",
    "https://www.bodybuilding.com/exercises/reverse-flyes",
    "https://www.bodybuilding.com/exercises/step-mill",
    "https://www.bodybuilding.com/exercises/elbow-to-knee",
    "https://www.bodybuilding.com/exercises/kettlebell-pistol-squat",
    "https://www.bodybuilding.com/exercises/standing-dumbbell-straight-arm-front-delt-raise-above-head",
    "https://www.bodybuilding.com/exercises/biceps-curl-to-shoulder-press",
    "https://www.bodybuilding.com/exercises/weighted-bench-dip",
    "https://www.bodybuilding.com/exercises/barbell-hip-thrust",
    "https://www.bodybuilding.com/exercises/bodyweight-lunge",
    "https://www.bodybuilding.com/exercises/barbell-bench-press-medium-grip",
    "https://www.bodybuilding.com/exercises/dips-chest-version",
    "https://www.bodybuilding.com/exercises/dumbbell-shoulder-press",
    "https://www.bodybuilding.com/exercises/barbell-curl",
    "https://www.bodybuilding.com/exercises/ez-bar-skullcrusher",
    "https://www.bodybuilding.com/exercises/one-arm-dumbbell-row",
    "https://www.bodybuilding.com/exercises/standing-alternating-dumbbell-press",
    "https://www.bodybuilding.com/exercises/concentration-curls",
    "https://www.bodybuilding.com/exercises/decline-crunch",
    "https://www.bodybuilding.com/exercises/decline-dumbbell-flyes",
    "https://www.bodybuilding.com/exercises/dumbbell-lying-one-arm-rear-lateral-raise",
    "https://www.bodybuilding.com/exercises/front-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/hanging-pike",
    "https://www.bodybuilding.com/exercises/narrow-stance-squats",
    "https://www.bodybuilding.com/exercises/oblique-cable-crunch",
    "https://www.bodybuilding.com/exercises/reverse-grip-triceps-pushdown",
    "https://www.bodybuilding.com/exercises/bear-crawl-sled-drags-",
    "https://www.bodybuilding.com/exercises/rocky-pull-upspulldowns",
    "https://www.bodybuilding.com/exercises/snatch-grip-behind-the-neck-overhead-press",
    "https://www.bodybuilding.com/exercises/box-squat-with-bands",
    "https://www.bodybuilding.com/exercises/flexor-incline-dumbbell-curls",
    "https://www.bodybuilding.com/exercises/seated-one-arm-dumbbell-palms-up-wrist-curl",
    "https://www.bodybuilding.com/exercises/thigh-adductor",
    "https://www.bodybuilding.com/exercises/machine-bicep-curl",
    "https://www.bodybuilding.com/exercises/seated-palms-down-barbell-wrist-curl",
    "https://www.bodybuilding.com/exercises/dumbbell-lying-one-arm-rear-lateral-raise",
    "https://www.bodybuilding.com/exercises/front-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/hanging-pike",
    "https://www.bodybuilding.com/exercises/narrow-stance-squats",
    "https://www.bodybuilding.com/exercises/oblique-cable-crunch",
    "https://www.bodybuilding.com/exercises/reverse-grip-triceps-pushdown",
    "https://www.bodybuilding.com/exercises/bear-crawl-sled-drags-",
    "https://www.bodybuilding.com/exercises/rocky-pull-upspulldowns",
    "https://www.bodybuilding.com/exercises/snatch-grip-behind-the-neck-overhead-press",
    "https://www.bodybuilding.com/exercises/box-squat-with-bands",
    "https://www.bodybuilding.com/exercises/flexor-incline-dumbbell-curls",
    "https://www.bodybuilding.com/exercises/seated-one-arm-dumbbell-palms-up-wrist-curl",
    "https://www.bodybuilding.com/exercises/machine-bicep-curl",
    "https://www.bodybuilding.com/exercises/seated-palms-down-barbell-wrist-curl",
    "https://www.bodybuilding.com/exercises/car-drivers",
    "https://www.bodybuilding.com/exercises/alternating-deltoid-raise",
    "https://www.bodybuilding.com/exercises/hanging-oblique-knee-raise",
    "https://www.bodybuilding.com/exercises/bodyweight-flyes",
    "https://www.bodybuilding.com/exercises/standing-calf-raises",
    "https://www.bodybuilding.com/exercises/push-ups-close-triceps-position",
    "https://www.bodybuilding.com/exercises/one-arm-long-bar-row",
    "https://www.bodybuilding.com/exercises/overhead-cable-curl",
    "https://www.bodybuilding.com/exercises/single-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/incline-cable-flye",
    "https://www.bodybuilding.com/exercises/single-leg-high-box-squat",
    "https://www.bodybuilding.com/exercises/weighted-suitcase-crunch",
    "https://www.bodybuilding.com/exercises/plate-twist",
    "https://www.bodybuilding.com/exercises/one-legged-cable-kickback",
    "https://www.bodybuilding.com/exercises/weighted-jump-squat-",
    "https://www.bodybuilding.com/exercises/squat-with-chains",
    "https://www.bodybuilding.com/exercises/gorilla-chincrunch",
    "https://www.bodybuilding.com/exercises/kneeling-cable-triceps-extension",
    "https://www.bodybuilding.com/exercises/kneeling-cable-crunch-with-alternating-oblique-twists",
    "https://www.bodybuilding.com/exercises/bicycling",
    "https://www.bodybuilding.com/exercises/arnold-dumbbell-press",
    "https://www.bodybuilding.com/exercises/weighted-crunches",
    "https://www.bodybuilding.com/exercises/cable-one-arm-tricep-extension",
    "https://www.bodybuilding.com/exercises/barbell-ab-rollout",
    "https://www.bodybuilding.com/exercises/cable-crunch",
    "https://www.bodybuilding.com/exercises/exercise-ball-pull-in",
    "https://www.bodybuilding.com/exercises/hanging-leg-raise",
    "https://www.bodybuilding.com/exercises/barbell-ab-rollout-on-knees",
    "https://www.bodybuilding.com/exercises/barbell-squat",
    "https://www.bodybuilding.com/exercises/decline-barbell-bench-press",
    "https://www.bodybuilding.com/exercises/dumbbell-bicep-curl",
    "https://www.bodybuilding.com/exercises/dumbbell-goblet-squat",
    "https://www.bodybuilding.com/exercises/dumbbell-squat",
    "https://www.bodybuilding.com/exercises/front-barbell-squat",
    "https://www.bodybuilding.com/exercises/v-bar-pulldown",
    "https://www.bodybuilding.com/exercises/triceps-pushdown-rope-attachment",
    "https://www.bodybuilding.com/exercises/side-to-side-box-shuffle",
    "https://www.bodybuilding.com/exercises/smith-machine-overhead-shoulder-press",
    "https://www.bodybuilding.com/exercises/seated-triceps-press",
    "https://www.bodybuilding.com/exercises/dumbbell-lying-supination",
    "https://www.bodybuilding.com/exercises/wide-grip-pull-up",
    "https://www.bodybuilding.com/exercises/wide-grip-barbell-bench-press",
    "https://www.bodybuilding.com/exercises/close-grip-ez-bar-curl",
    "https://www.bodybuilding.com/exercises/t-bar-row",
    "https://www.bodybuilding.com/exercises/bent-over-two-arm-long-bar-row",
    "https://www.bodybuilding.com/exercises/muscle-up",
    "https://www.bodybuilding.com/exercises/leverage-shoulder-press",
    "https://www.bodybuilding.com/exercises/incline-barbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/bent-over-one-arm-long-bar-row",
    "https://www.bodybuilding.com/exercises/wide-grip-decline-barbell-bench-press",
    "https://www.bodybuilding.com/exercises/rowing-stationary",
    "https://www.bodybuilding.com/exercises/snatch-deadlift",
    "https://www.bodybuilding.com/exercises/front-plate-raise",
    "https://www.bodybuilding.com/exercises/decline-close-grip-bench-to-skull-crusher",
    "https://www.bodybuilding.com/exercises/lying-leg-curls",
    "https://www.bodybuilding.com/exercises/cross-body-hammer-curl",
    "https://www.bodybuilding.com/exercises/shotgun-row",
    "https://www.bodybuilding.com/exercises/ab-roller",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-press-reverse-grip",
    "https://www.bodybuilding.com/exercises/leg-press",
    "https://www.bodybuilding.com/exercises/stiff-legged-dumbbell-deadlift",
    "https://www.bodybuilding.com/exercises/cable-crossover",
    "https://www.bodybuilding.com/exercises/barbell-incline-bench-press-medium-grip",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-flyes",
    "https://www.bodybuilding.com/exercises/seated-cable-rows",
    "https://www.bodybuilding.com/exercises/tricep-dumbbell-kickback",
    "https://www.bodybuilding.com/exercises/otis-up",
    "https://www.bodybuilding.com/exercises/mountain-climbers",
    "https://www.bodybuilding.com/exercises/air-bike",
    "https://www.bodybuilding.com/exercises/barbell-lunge",
    "https://www.bodybuilding.com/exercises/34-sit-up",
    "https://www.bodybuilding.com/exercises/ball-leg-curl",
    "https://www.bodybuilding.com/exercises/butt-lift-bridge",
    "https://www.bodybuilding.com/exercises/close-grip-front-lat-pulldown",
    "https://www.bodybuilding.com/exercises/dip-machine",
    "https://www.bodybuilding.com/exercises/dumbbell-incline-row",
    "https://www.bodybuilding.com/exercises/dumbbell-lunges",
    "https://www.bodybuilding.com/exercises/dumbbell-one-arm-shoulder-press",
    "https://www.bodybuilding.com/exercises/preacher-curl",
    "https://www.bodybuilding.com/exercises/reverse-crunch",
    "https://www.bodybuilding.com/exercises/standing-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/elliptical-trainer",
    "https://www.bodybuilding.com/exercises/bodyweight-squat",
    "https://www.bodybuilding.com/exercises/bent-over-two-dumbbell-row-with-palms-in",
    "https://www.bodybuilding.com/exercises/trap-bar-deadlift",
    "https://www.bodybuilding.com/exercises/narrow-stance-leg-press",
    "https://www.bodybuilding.com/exercises/single-leg-glute-bridge",
    "https://www.bodybuilding.com/exercises/barbell-curls-lying-against-an-incline",
    "https://www.bodybuilding.com/exercises/standing-hip-circles",
    "https://www.bodybuilding.com/exercises/clam",
    "https://www.bodybuilding.com/exercises/narrow-stance-hack-squats",
    "https://www.bodybuilding.com/exercises/seated-close-grip-concentration-barbell-curl",
    "https://www.bodybuilding.com/exercises/dumbbell-lying-pronation",
    "https://www.bodybuilding.com/exercises/chair-squat",
    "https://www.bodybuilding.com/exercises/drop-push",
    "https://www.bodybuilding.com/exercises/bodyweight-mid-row",
    "https://www.bodybuilding.com/exercises/reverse-barbell-preacher-curls",
    "https://www.bodybuilding.com/exercises/close-grip-ez-bar-press",
    "https://www.bodybuilding.com/exercises/incline-push-up",
    "https://www.bodybuilding.com/exercises/hyperextensions-with-no-hyperextension-bench",
    "https://www.bodybuilding.com/exercises/front-two-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/parallel-bar-dip",
    "https://www.bodybuilding.com/exercises/stairmaster",
    "https://www.bodybuilding.com/exercises/double-leg-butt-kick",
    "https://www.bodybuilding.com/exercises/groiners-",
    "https://www.bodybuilding.com/exercises/neck-press",
    "https://www.bodybuilding.com/exercises/standing-long-jump",
    "https://www.bodybuilding.com/exercises/machine-squat",
    "https://www.bodybuilding.com/exercises/v-bar-pullup",
    "https://www.bodybuilding.com/exercises/ring-dips",
    "https://www.bodybuilding.com/exercises/standing-one-arm-cable-curl",
    "https://www.bodybuilding.com/exercises/burpee",
    "https://www.bodybuilding.com/exercises/standing-bent-over-two-arm-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/dumbbell-rear-lunge",
    "https://www.bodybuilding.com/exercises/seated-calf-raise",
    "https://www.bodybuilding.com/exercises/dumbbell-shrug",
    "https://www.bodybuilding.com/exercises/calf-press-on-the-leg-press-machine",
    "https://www.bodybuilding.com/exercises/barbell-step-ups",
    "https://www.bodybuilding.com/exercises/bench-dips",
    "https://www.bodybuilding.com/exercises/bent-over-barbell-row",
    "https://www.bodybuilding.com/exercises/crunches",
    "https://www.bodybuilding.com/exercises/dumbbell-alternate-bicep-curl",
    "https://www.bodybuilding.com/exercises/dumbbell-rear-delt-row",
    "https://www.bodybuilding.com/exercises/external-rotation-with-cable",
    "https://www.bodybuilding.com/exercises/handstand-push-ups",
    "https://www.bodybuilding.com/exercises/one-arm-dumbbell-preacher-curl",
    "https://www.bodybuilding.com/exercises/step-up-with-knee-raise",
    "https://www.bodybuilding.com/exercises/smith-machine-squat",
    "https://www.bodybuilding.com/exercises/front-incline-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/alternate-incline-dumbbell-curl",
    "https://www.bodybuilding.com/exercises/standing-dumbbell-upright-row",
    "https://www.bodybuilding.com/exercises/front-cable-raise",
    "https://www.bodybuilding.com/exercises/two-arm-kettlebell-military-press",
    "https://www.bodybuilding.com/exercises/incline-cable-chest-press",
    "https://www.bodybuilding.com/exercises/rope-climb",
    "https://www.bodybuilding.com/exercises/one-arm-dumbbell-preacher-curl",
    "https://www.bodybuilding.com/exercises/step-up-with-knee-raise",
    "https://www.bodybuilding.com/exercises/front-incline-dumbbell-raise",
    "https://www.bodybuilding.com/exercises/rope-climb",
    "https://www.bodybuilding.com/exercises/trail-runningwalking",
    "https://www.bodybuilding.com/exercises/standing-bradford-press",
    "https://www.bodybuilding.com/exercises/dumbbell-bench-press-with-neutral-grip",
    "https://www.bodybuilding.com/exercises/cable-chest-press",
    "https://www.bodybuilding.com/exercises/standing-concentration-curl",
    "https://www.bodybuilding.com/exercises/wide-grip-rear-pull-up",
    "https://www.bodybuilding.com/exercises/lunge-pass-through",
    "https://www.bodybuilding.com/exercises/incline-push-up-medium",
    "https://www.bodybuilding.com/exercises/deadlift-with-bands",
    "https://www.bodybuilding.com/exercises/rope-straight-arm-pulldown",
    "https://www.bodybuilding.com/exercises/barbell-shoulder-press",
    "https://www.bodybuilding.com/exercises/power-clean",
    "https://www.bodybuilding.com/exercises/hang-snatch",
    "https://www.bodybuilding.com/exercises/kettlebell-sumo-high-pull",
    "https://www.bodybuilding.com/exercises/calf-machine-shoulder-shrug",
    "https://www.bodybuilding.com/exercises/bench-press-powerlifting",
    "https://www.bodybuilding.com/exercises/rocking-standing-calf-raise",
    "https://www.bodybuilding.com/exercises/goblet-squat",
    "https://www.bodybuilding.com/exercises/lying-close-grip-barbell-triceps-extension-behind-the-head",
    "https://www.bodybuilding.com/exercises/seated-palm-up-barbell-wrist-curl",
    "https://www.bodybuilding.com/exercises/reverse-cable-curl",
    "https://www.bodybuilding.com/exercises/dumbbell-side-bend",
    "https://www.bodybuilding.com/exercises/wide-grip-lat-pulldown",
    "https://www.bodybuilding.com/exercises/side-lateral-raise",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-curl",
    "https://www.bodybuilding.com/exercises/kettlebell-one-legged-deadlift",
    "https://www.bodybuilding.com/exercises/alternate-hammer-curl",
    "https://www.bodybuilding.com/exercises/decline-push-up",
    "https://www.bodybuilding.com/exercises/kneehip-raise-on-parallel-bars",
    "https://www.bodybuilding.com/exercises/triceps-pushdown",
    "https://www.bodybuilding.com/exercises/triceps-overhead-extension-with-rope",
    "https://www.bodybuilding.com/exercises/single-arm-cable-crossover",
    "https://www.bodybuilding.com/exercises/seated-dumbbell-curl",
    "https://www.bodybuilding.com/exercises/battling-ropes",
    "https://www.bodybuilding.com/exercises/dead-bug",
    "https://www.bodybuilding.com/exercises/deadlift-with-chains",
    "https://www.bodybuilding.com/exercises/rope-crunch",
    "https://www.bodybuilding.com/exercises/palms-up-dumbbell-wrist-curl-over-a-bench",
    "https://www.bodybuilding.com/exercises/kettlebell-thruster",
    "https://www.bodybuilding.com/exercises/single-arm-push-up",
    "https://www.bodybuilding.com/exercises/band-hip-adductions",
    "https://www.bodybuilding.com/exercises/one-arm-kettlebell-clean",
    "https://www.bodybuilding.com/exercises/preacher-hammer-dumbbell-curl",
    "https://www.bodybuilding.com/exercises/alternating-kettlebell-press",
    "https://www.bodybuilding.com/exercises/split-squat-with-dumbbells",
    "https://www.bodybuilding.com/exercises/standing-one-arm-dumbbell-curl-over-incline-bench",
    "https://www.bodybuilding.com/exercises/standing-olympic-plate-hand-squeeze",
    "https://www.bodybuilding.com/exercises/sledgehammer-swings",
    "https://www.bodybuilding.com/exercises/kneeling-squat",
    "https://www.bodybuilding.com/exercises/one-arm-kettlebell-snatch",
    "https://www.bodybuilding.com/exercises/close-grip-standing-barbell-curl",
    "https://www.bodybuilding.com/exercises/front-box-jump",
    "https://www.bodybuilding.com/exercises/standing-rope-crunch",
    "https://www.bodybuilding.com/exercises/leverage-incline-chest-press",
    "https://www.bodybuilding.com/exercises/standing-overhead-barbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/cable-lying-triceps-extension",
    "https://www.bodybuilding.com/exercises/kettlebell-turkish-get-up-squat-style",
    "https://www.bodybuilding.com/exercises/crunch-hands-overhead",
    "https://www.bodybuilding.com/exercises/cable-internal-rotation",
    "https://www.bodybuilding.com/exercises/leg-extensions",
    "https://www.bodybuilding.com/exercises/standing-one-arm-dumbbell-curl-over-incline-bench",
    "https://www.bodybuilding.com/exercises/standing-olympic-plate-hand-squeeze",
    "https://www.bodybuilding.com/exercises/sledgehammer-swings",
    "https://www.bodybuilding.com/exercises/one-arm-kettlebell-snatch",
    "https://www.bodybuilding.com/exercises/front-box-jump",
    "https://www.bodybuilding.com/exercises/standing-rope-crunch",
    "https://www.bodybuilding.com/exercises/standing-overhead-barbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/cable-lying-triceps-extension",
    "https://www.bodybuilding.com/exercises/pushups-close-and-wide-hand-positions",
    "https://www.bodybuilding.com/exercises/dumbbell-one-arm-triceps-extension",
    "https://www.bodybuilding.com/exercises/butterfly",
    "https://www.bodybuilding.com/exercises/decline-dumbbell-bench-press",
    "https://www.bodybuilding.com/exercises/jackknife-sit-up",
    "https://www.bodybuilding.com/exercises/low-pulley-row-to-neck",
    "https://www.bodybuilding.com/exercises/one-leg-barbell-squat",
    "https://www.bodybuilding.com/exercises/underhand-cable-pulldowns",
    "https://www.bodybuilding.com/exercises/standing-biceps-cable-curl",
    "https://www.bodybuilding.com/exercises/seated-one-arm-cable-pulley-rows",
    "https://www.bodybuilding.com/exercises/one-arm-dumbbell-bench-press",
    "https://www.bodybuilding.com/exercises/scissors-jump",
    "https://www.bodybuilding.com/exercises/wide-stance-stiff-legs",
    "https://www.bodybuilding.com/exercises/rack-pull-with-bands",
    "https://www.bodybuilding.com/exercises/drag-curl",
    "https://www.bodybuilding.com/exercises/pushups-close-and-wide-hand-positions",
    "https://www.bodybuilding.com/exercises/dumbbell-one-arm-triceps-extension",
    "https://www.bodybuilding.com/exercises/butterfly",
    "https://www.bodybuilding.com/exercises/low-pulley-row-to-neck",
    "https://www.bodybuilding.com/exercises/rack-pull-with-bands",
    "https://www.bodybuilding.com/exercises/drag-curl",
    "https://www.bodybuilding.com/exercises/hang-clean-below-the-knees",
    "https://www.bodybuilding.com/exercises/decline-oblique-crunch",
    "https://www.bodybuilding.com/exercises/external-rotation",
    "https://www.bodybuilding.com/exercises/bent-over-low-pulley-side-lateral",
    "https://www.bodybuilding.com/exercises/clean",
    "https://www.bodybuilding.com/exercises/one-arm-incline-lateral-raise",
    "https://www.bodybuilding.com/exercises/press-sit-up",
    "https://www.bodybuilding.com/exercises/barbell-rear-delt-row",
    "https://www.bodybuilding.com/exercises/calf-press",
    "https://www.bodybuilding.com/exercises/alternating-renegade-row",
    "https://www.bodybuilding.com/exercises/bosu-ball-cable-crunch-with-side-bends",
    "https://www.bodybuilding.com/exercises/stomach-vacuum",
    "https://www.bodybuilding.com/exercises/hammer-grip-incline-db-bench-press",
    "https://www.bodybuilding.com/exercises/incline-push-up-wide",
    "https://www.bodybuilding.com/exercises/decline-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/jumping-jacks",
    "https://www.bodybuilding.com/exercises/push-ups-with-feet-on-an-exercise-ball",
    "https://www.bodybuilding.com/exercises/seated-cable-shoulder-press",
    "https://www.bodybuilding.com/exercises/barbell-hack-squat",
    "https://www.bodybuilding.com/exercises/push-ups-with-feet-elevated",
    "https://www.bodybuilding.com/exercises/good-morning",
    "https://www.bodybuilding.com/exercises/leverage-chest-press",
    "https://www.bodybuilding.com/exercises/gironda-sternum-chins",
    "https://www.bodybuilding.com/exercises/exercise-ball-crunch",
    "https://www.bodybuilding.com/exercises/seated-bent-over-rear-delt-raise",
    "https://www.bodybuilding.com/exercises/face-pull",
    "https://www.bodybuilding.com/exercises/glute-ham-raise",
    "https://www.bodybuilding.com/exercises/russian-twist",
    "https://www.bodybuilding.com/exercises/seated-flat-bench-leg-pull-in",
    "https://www.bodybuilding.com/exercises/barbell-shrug",
    "https://www.bodybuilding.com/exercises/seated-flat-bench-leg-pull-in",
    "https://www.bodybuilding.com/exercises/barbell-shrug",
    "https://www.bodybuilding.com/exercises/cable-rope-rear-delt-rows",
    "https://www.bodybuilding.com/exercises/flat-bench-lying-leg-raise",
    "https://www.bodybuilding.com/exercises/hack-squat",
    "https://www.bodybuilding.com/exercises/lying-dumbbell-tricep-extension",
    "https://www.bodybuilding.com/exercises/man-maker",
    "https://www.bodybuilding.com/exercises/pallof-press",
    "https://www.bodybuilding.com/exercises/tuck-crunch",
    "https://www.bodybuilding.com/exercises/straight-arm-dumbbell-pullover",
    "https://www.bodybuilding.com/exercises/freehand-jump-squat",
    "https://www.bodybuilding.com/exercises/decline-smith-press",
    "https://www.bodybuilding.com/exercises/band-skull-crusher",
    "https://www.bodybuilding.com/exercises/side-wrist-pull",
    "https://www.bodybuilding.com/exercises/isometric-wipers",
    "https://www.bodybuilding.com/exercises/skating",
    "https://www.bodybuilding.com/exercises/cable-iron-cross",
    "https://www.bodybuilding.com/exercises/running-treadmill",
    "https://www.bodybuilding.com/exercises/one-arm-pronated-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/one-arm-kettlebell-clean-and-jerk-",
    "https://www.bodybuilding.com/exercises/side-to-side-chins",
    "https://www.bodybuilding.com/exercises/incline-dumbbell-bench-with-palms-facing-in",
    "https://www.bodybuilding.com/exercises/seated-dumbbell-palms-down-wrist-curl",
    "https://www.bodybuilding.com/exercises/front-leg-raises",
    "https://www.bodybuilding.com/exercises/clock-push-up",
    "https://www.bodybuilding.com/exercises/leverage-iso-row",
    "https://www.bodybuilding.com/exercises/lying-face-up-plate-neck-resistance",
    "https://www.bodybuilding.com/exercises/weighted-sissy-squat",
    "https://www.bodybuilding.com/exercises/jog-in-place",
    "https://www.bodybuilding.com/exercises/dumbbell-raise",
    "https://www.bodybuilding.com/exercises/palms-down-dumbbell-wrist-curl-over-a-bench",
    "https://www.bodybuilding.com/exercises/one-arm-supinated-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/jog-in-place",
    "https://www.bodybuilding.com/exercises/dumbbell-raise",
    "https://www.bodybuilding.com/exercises/palms-down-dumbbell-wrist-curl-over-a-bench",
    "https://www.bodybuilding.com/exercises/one-arm-supinated-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/bicycling-stationary",
    "https://www.bodybuilding.com/exercises/bent-over-two-dumbbell-row",
    "https://www.bodybuilding.com/exercises/barbell-thruster",
    "https://www.bodybuilding.com/exercises/flutter-kicks",
    "https://www.bodybuilding.com/exercises/plie-dumbbell-squat",
    "https://www.bodybuilding.com/exercises/upright-barbell-row",
    "https://www.bodybuilding.com/exercises/superman",
    "https://www.bodybuilding.com/exercises/straight-arm-pulldown",
    "https://www.bodybuilding.com/exercises/stiff-legged-barbell-deadlift",
    "https://www.bodybuilding.com/exercises/standing-one-arm-dumbbell-triceps-extension",
    "https://www.bodybuilding.com/exercises/smith-machine-bench-press",
    "https://www.bodybuilding.com/exercises/seated-side-lateral-raise",
    "https://www.bodybuilding.com/exercises/dumbbell-lying-rear-lateral-raise",
    "https://www.bodybuilding.com/exercises/two-arm-dumbbell-preacher-curl",
    "https://www.bodybuilding.com/exercises/front-raise-and-pullover",
    "https://www.bodybuilding.com/exercises/dumbbell-seated-box-jump",
    "https://www.bodybuilding.com/exercises/middle-back-shrug",
    "https://www.bodybuilding.com/exercises/straight-raises-on-incline-bench",
    "https://www.bodybuilding.com/exercises/butt-ups",
    "https://www.bodybuilding.com/exercises/band-good-morning-pull-through",
    "https://www.bodybuilding.com/exercises/bodyweight-reverse-lunge",
    "https://www.bodybuilding.com/exercises/seated-one-arm-dumbbell-palms-down-wrist-curl",
    "https://www.bodybuilding.com/exercises/glute-kickback",
    "https://www.bodybuilding.com/exercises/jogging-treadmill",
    "https://www.bodybuilding.com/exercises/plate-pinch",
    "https://www.bodybuilding.com/exercises/yates-row-reverse-grip",
    "https://www.bodybuilding.com/exercises/linear-acceleration-wall-drill",
    "https://www.bodybuilding.com/exercises/reverse-triceps-bench-press",
    "https://www.bodybuilding.com/exercises/leverage-decline-chest-press",
    "https://www.bodybuilding.com/exercises/chain-handle-extension",
]

data = []

with tqdm(total=len(urls), desc="Processing URLs") as pbar:
    for url in urls:
        response = requests.get(url)
        content = response.content

        soup = BeautifulSoup(content, "html.parser")

        name = soup.find("h1", class_="ExHeading ExHeading--h2 ExDetail-h2").text.strip()
        images = soup.findAll("img", class_="ExImg ExDetail-img js-ex-enlarge")

        # Error handling for missing description:
        description_element = soup.find("div", class_="ExDetail-shortDescription")
        if description_element and description_element.find("p"):
            description = description_element.find("p").get_text().strip()
        else:
            description = ""

        all_li_elements = soup.find("ul", class_="bb-list--plain").find_all("li")

        type = all_li_elements[0].find("a").text.strip() if all_li_elements and all_li_elements[0].find("a") else ""
        muscle = all_li_elements[1].find("a").text.strip() if len(all_li_elements) >= 2 and all_li_elements[1].find("a") else ""
        equipment = all_li_elements[2].find("a").text.strip() if len(all_li_elements) >= 3 and all_li_elements[2].find("a") else ""
        level = all_li_elements[3].text[25:].strip() if len(all_li_elements) >= 4 else ""  # Extract level concisely

        image_urls = [image["src"] for image in images]  # Collect image URLs in a list

        data.append({
            "exercise_name": name,
            "description": description,
            "image_1": image_urls[0] if len(image_urls) > 0 else "",  # Handle potential missing images
            "image_2": image_urls[1] if len(image_urls) > 1 else "",
            "image_3": image_urls[2] if len(image_urls) > 2 else "",
            "image_4": image_urls[3] if len(image_urls) > 3 else "",
            "type": type,
            "muscle_group": muscle,
            "equipment": equipment,
            "level": level
        })

        pbar.update(1)

# Create a DataFrame and export to XLSX:
print("Creating exercise_data.xlsx")
df = pd.DataFrame(data)
df.to_excel("exercise_data.xlsx", index=False)  # Don't include an index column

print("Dataset completed")