# Generated by Django 5.0 on 2023-12-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exercise_description_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
