# Generated by Django 5.0 on 2024-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exercise_image1_alter_exercise_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
